M48
; DRILL file KiCad 10.0.6 date 2026-09-01T02:00:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T02:00:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X79.62Y-23.83
X85.4Y-23.83
T2
X102.26Y-22.55
T3
X102.26Y-27.05
M30
